apiVersion: v1
kind: List
- apiVersion: v1
  kind: Service
  metadata:
    name: simple-web-app-service   # Name of the resource
    labels:
        app: simple-web-app
  spec:
    type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
    selector:
        app: simple-web-app
    ports:  
    - protocol: TCP                       # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
    - name: http
        port: 9090
        targetPort: 8080
