apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-web-app
spec:
  maxReplicas: 8
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-web-app
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 20
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 100Mi